service: serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "ses:SendEmail"
            - "ses:SendRawEmail"
            - "ses:SendTemplatedEmail"
          Resource: "*"

functions:
  send_template_mail:
    handler: handler.send_template_mail
