service: sendMailAPI
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  httpApi:
    name: sendSimpleMail

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "ses:SendEmail"
            - "ses:SendRawEmail"
            - "ses:SendTemplatedEmail"
          Resource: "*"

functions:
  send_template_mail:
    handler: handler.send_template_mail
    events: 
      - httpApi:
          path: /mail/send-template
          method: POST
          cors:
            allowedMethods: ['POST']
            allowedHeaders:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
            maxAge: 3600
          request:
            parameters:
              paths:
                sender_name: true
                source_email: true
                template_subject: true
                template_body: true
          httpApiEvent:
            method: POST
            path: /mail/send-template
            throttling:
              burstLimit: 5
              rateLimit: 2
            authorizer: aws.iam