service: sendMailAPI
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  httpApi:
    name: sendSimpleMail

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "ses:SendEmail"
            - "ses:SendRawEmail"
            - "ses:SendTemplatedEmail"
          Resource: "*"

functions:
  send_template_mail:
    handler: handler.dispatch
    events: 
      - httpApi:
          path: /mail/send-template
          method: POST
      - httpApi:
          path: /mail/send-template
          method: OPTIONS

plugins:
  - serverless-api-gateway-throttling

custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 0.0001157
    maxConcurrentRequests: 2

# Monthly limit = 300 requests
# Number of seconds in a month:
#   = 30 days * 24 hours * 60 minutes * 60 seconds = 2,592,000 seconds
# Rate limit per second 
# = Monthly limit / Number of seconds in a month
# = 300 / 2,592,000
# ≈ 0.0001157

# Max concurrent requests = 2 (because send two emails at a time)
