service: sendMailAPI
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  httpApi:
    name: sendSimpleMail

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "ses:SendEmail"
            - "ses:SendRawEmail"
            - "ses:SendTemplatedEmail"
          Resource: "*"

functions:
  send_template_mail:
    handler: handler.dispatch
    events: 
      - httpApi:
          path: /mail/send-template
          method: POST
      - httpApi:
          path: /mail/send-template
          method: OPTIONS
