service: sendMailAPI
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  httpApi:
    name: sendSimpleMail

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
            - "ses:SendEmail"
            - "ses:SendRawEmail"
            - "ses:SendTemplatedEmail"
          Resource: "*"

functions:
  send_template_mail:
    handler: handler.dispatch
    events: 
      - httpApi:
          path: /mail/send-template
          method: POST
          cors:
            origins:
              - 'https://felipecastrosales.com'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowOrigins:
              - 'https://felipecastrosales.com'
            allowMethods:
              - ['POST', 'OPTIONS']
            allowHeaders:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
            maxAge: 1
          response:
            headers:
              Access-Control-Allow-Origin: '*'
              Access-Control-Allow-Headers: 'Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token, X-Amz-User-Agent'
              Access-Control-Allow-Credentials: true
          request:
            parameters:
              paths:
                sender_name: true
                source_email: true
                template_subject: true
                template_body: true
          httpApiEvent:
            method: POST
            path: /mail/send-template
            throttling:
              # Monthly limit = 300 requests
              # Number of seconds in a month:
              #   = 30 days * 24 hours * 60 minutes * 60 seconds = 2,592,000 seconds
              # Rate limit per second 
              # = Monthly limit / Number of seconds in a month
              # = 300 / 2,592,000
              # ≈ 0.0001157
              burstLimit: 0.0001157
              rateLimit: 2
            authorizer: aws.iam
      - httpApi:
          path: /mail/send-template
          method: OPTIONS
          cors:
            origins:
              - 'https://felipecastrosales.com'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowOrigins:
              - 'https://felipecastrosales.com'
            allowMethods:
              - ['POST', 'OPTIONS']
            allowHeaders:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
            maxAge: 1
          response:
            headers:
              Access-Control-Allow-Origin: '*'
              Access-Control-Allow-Headers: 'Content-Type, Authorization, X-Amz-Date, X-Api-Key, X-Amz-Security-Token, X-Amz-User-Agent'
              Access-Control-Allow-Credentials: true
          request:
            parameters:
              paths:
                sender_name: true
                source_email: true
                template_subject: true
                template_body: true
          httpApiEvent:
            method: POST
            path: /mail/send-template
            throttling:
              # Monthly limit = 300 requests
              # Number of seconds in a month:
              #   = 30 days * 24 hours * 60 minutes * 60 seconds = 2,592,000 seconds
              # Rate limit per second 
              # = Monthly limit / Number of seconds in a month
              # = 300 / 2,592,000
              # ≈ 0.0001157
              burstLimit: 0.0001157
              rateLimit: 2
            authorizer: aws.iam
